Repository AI-Play/ML-Train, pull requests merged in 2022-03, with the labels that each got.

#34 [FeatureMade] 20220303 fit, transform, steps
  functions/__init__.py
  functions/make_model.py
  functions/model_functions.py
  main.py
Labels: 분류: 기능 구현

#39 [FeatureMade][BugFix] model_predict, model_score 기능구현, fit, transform 버그 수정
  functions/make_model.py
  functions/model_functions.py
Labels: 분류: 기능 구현, 분류: 버그

#42 [FeatureMade] 20220312 에러체크 기능 추가, 이슈 해결
  functions/internal_func.py
  functions/make_model.py
  functions/model_functions.py
Labels: 분류: 기능 구현, 분류: 버그

#44 [FeatureMade] 20220314 make_optimizer, model_step_detail
  functions/__init__.py
  functions/internal_func.py
  functions/make_model.py
  functions/model_functions.py
  main.py
Labels: 분류: 기능 구현, 분류: 기능 추가 요청

#45 [FeatureEdit] 20220315 predict, score
  functions/make_model.py
  functions/model_functions.py
Labels: 분류: 기능 추가 요청

#46 [FeatureEdit] 20220315 fit 함수에 fit_optimizer 기능 추가
  functions/internal_func.py
  functions/model_functions.py
Labels: 분류: 기능 추가 요청

#47 [FeatureMade][BugFix] postgres func_log 기능 구현 및 각 종 버그 픽스
  .gitignore
  functions/__init__.py
  functions/internal_func.py
  functions/make_model.py
  functions/model_functions.py
  main.py
Labels: 분류: 기능 구현, 분류: 버그

#48 [FeatureMade] .env setting updated
  config.py
  functions/internal_func.py
  requirements.txt
Labels: 분류: 기능 구현

#49 [FeatureMade] CORS Origins updated
  main.py
Labels: 분류: 기능 구현

#50 requirements.txt updated
  requirements.txt
Labels: 분류: 문서화
